# -*- coding: utf-8 -*-
"""
Generates data/category-overrides.json from hand-classified 其他 items.
Run: python3 pipeline/overrides.py
"""
import json, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'data'

# URL -> (category, subcategory|None)
OVERRIDES = {
    # ── Batch 1 ──────────────────────────────────────────────────────────────
    "https://www.threads.com/@vittorio.dacunzo/post/DXz8CxPk5S2": ("口誤", "職場口誤"),
    "https://www.threads.com/@gil9/post/DX3OxpLkVhX": ("其他", None),
    "https://www.threads.com/@dream_illusion_bubble_shadow/post/DXzz5G5k7wB": ("當眾出糗", None),
    "https://www.threads.com/@krisyenyen/post/DX11OAEAV-5": ("當眾出糗", None),
    "https://www.threads.com/@yiiiiiiiichennnnnnnn/post/DX1DrKEkU6M": ("其他", None),
    "https://www.threads.com/@fukaiharunosumide/post/DX0_zHImOH5": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@emily.lin3737/post/DX1Wf9ekWIS": ("口誤", "語言混亂"),
    "https://www.threads.com/@yhn11999/post/DX10HPaE1Gw": ("口誤", "腦袋當機"),
    "https://www.threads.com/@imheidichin/post/DX4pgOGDx0v": ("口誤", "職場口誤"),
    "https://www.threads.com/@yihaw1/post/DX5UDZSgQ_T": ("被工作/兵役制約", None),
    "https://www.threads.com/@papajane518/post/DX1NcMyFFUx": ("當眾出糗", "工作中"),
    "https://www.threads.com/@boy7622/post/DX5LbLXk4M2": ("當眾出糗", "童言無忌"),
    "https://www.threads.com/@89.09.30/post/DX5QeOaj9UG": ("口誤", "腦袋當機"),
    "https://www.threads.com/@yiting207/post/DX1CB_3kXV1": ("其他", None),
    "https://www.threads.com/@drjjshaw/post/DX10WTvgWsZ": ("口誤", "乳頭/奶頭"),
    "https://www.threads.com/@hsumei_su/post/DX44UVyk2Pk": ("口誤", "語言混亂"),
    "https://www.threads.com/@yumibaby/post/DX1dwVfmcwy": ("回覆原 PO", None),
    "https://www.threads.com/@yumibaby/post/DX1eLsCGe9Q": ("回覆原 PO", None),
    "https://www.threads.com/@kenji7780/post/DX5GKoAk_b2": ("以為在跟自己說話", None),
    "https://www.threads.com/@betttyelizabeth/post/DX1Eh9Ck9pY": ("當眾出糗", None),
    "https://www.threads.com/@rikaka_hmng_2023/post/DX19UXYidJd": ("當眾出糗", None),
    "https://www.threads.com/@pjsk_yutsuki_1202/post/DX1cJNDE2Mb": ("其他", None),
    "https://www.threads.com/@bubblegum_1016/post/DX0XosciZzi": ("當眾出糗", None),
    "https://www.threads.com/@__7hzxn/post/DX46xIQE7Ta": ("其他", None),
    "https://www.threads.com/@kimhaha210/post/DX18ElfCc9I": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@winniebear131/post/DX2Bv0ij5OQ": ("口誤", "腦袋當機"),
    "https://www.threads.com/@stacccy_life/post/DX1X1TWGYLY": ("口誤", "腦袋當機"),
    "https://www.threads.com/@kuchienfen/post/DX1Wez8gRgj": ("當眾出糗", None),
    "https://www.threads.com/@kuchienfen/post/DX1u0aJAViT": ("回覆原 PO", None),
    "https://www.threads.com/@niuwubo/post/DX185FjEw4Q": ("口誤", "職場口誤"),
    "https://www.threads.com/@nini91120/post/DX1uDBPlN2q": ("當眾出糗", None),
    "https://www.threads.com/@nini91120/post/DX13OJjlCDG": ("回覆原 PO", None),
    "https://www.threads.com/@tsai.215/post/DX3Q1F_E8TO": ("其他", None),
    "https://www.threads.com/@wang.z.yuan.39/post/DX2n7_kk3Qg": ("口誤", "職場口誤"),
    "https://www.threads.com/@minna_3006/post/DX1Z3GyEt7K": ("口誤", "職場口誤"),
    "https://www.threads.com/@minna_3006/post/DX1cuRMEj9x": ("回覆原 PO", None),
    "https://www.threads.com/@lin.black.bear/post/DX1EfjqEbP5": ("以為沒人亂講話", None),
    "https://www.threads.com/@chia_o319/post/DX4yCp6ksWe": ("當眾出糗", "工作中"),
    "https://www.threads.com/@golden_sparkle791/post/DX1N_zcmGpc": ("口誤", "職場口誤"),
    "https://www.threads.com/@michelle.cms/post/DX2bF_2E1t-": ("當眾出糗", None),
    "https://www.threads.com/@shanglor2001/post/DX15G50ko-Q": ("其他", None),
    "https://www.threads.com/@yihaaann/post/DX0LUVcE2yQ": ("口誤", "腦袋當機"),
    "https://www.threads.com/@timmybrick/post/DXzqo1gE7nR": ("當眾出糗", None),
    "https://www.threads.com/@ddaphnewg/post/DX3k87sDazT": ("其他", None),
    "https://www.threads.com/@ddaphnewg/post/DX3lyf6DZaI": ("回覆原 PO", None),
    "https://www.threads.com/@lrc1119/post/DX1O67BD5VH": ("被工作/兵役制約", None),
    "https://www.threads.com/@bear_jie_729/post/DX1uinRCQBg": ("叫錯", "叫老師媽媽"),
    "https://www.threads.com/@hungchienjulia/post/DX2KgIxD5mp": ("當眾出糗", None),
    "https://www.threads.com/@yht2799/post/DX1E_K0mqoJ": ("口誤", "點餐/購物"),
    "https://www.threads.com/@lll_okawa/post/DX0vE5qE1Ab": ("當眾出糗", None),
    "https://www.threads.com/@0157_2000/post/DX11ko-j0__": ("當眾出糗", None),
    "https://www.threads.com/@ccemily816/post/DX0TOcVkiei": ("走錯空間", None),
    "https://www.threads.com/@lisa22666/post/DX3TIR_ESin": ("當眾出糗", None),
    "https://www.threads.com/@vickey_1001/post/DX1jKJtjxTB": ("口誤", "腦袋當機"),
    "https://www.threads.com/@gagarubylin/post/DX4rf_klUpy": ("當眾出糗", "工作中"),
    "https://www.threads.com/@yvonnehsieh467/post/DX2Mfxqk7PB": ("叫錯", "叫老師媽媽"),
    "https://www.threads.com/@a29586380/post/DX1cvVTE36g": ("當眾出糗", None),
    "https://www.threads.com/@e.sther_f/post/DX09MLjjwAw": ("當眾出糗", None),
    "https://www.threads.com/@sheau_chung_tang/post/DX3U3irEdQM": ("回覆原 PO", None),
    "https://www.threads.com/@miumiu_.0115/post/DX260vEkgRj": ("以為沒人亂講話", None),
    "https://www.threads.com/@ilovecat1229/post/DX1yiEVE0WH": ("當眾出糗", None),
    "https://www.threads.com/@yuliqbmq514/post/DX1_EBKmJ7J": ("叫錯", None),
    "https://www.threads.com/@coolcoolman7777/post/DX090VmE9-b": ("口誤", "點餐/購物"),
    "https://www.threads.com/@namaste_moon_33/post/DX3ci06kqHX": ("其他", None),
    "https://www.threads.com/@wei19861104/post/DX3fvn7Ey1r": ("回覆原 PO", None),
    "https://www.threads.com/@zzy._.0406/post/DX0-DaElNle": ("當眾出糗", None),
    "https://www.threads.com/@tcmasktw/post/DX5h02kjxam": ("以為沒人亂講話", None),
    "https://www.threads.com/@damn_82387/post/DX27sOLD5mi": ("當眾出糗", None),
    "https://www.threads.com/@kenshin1201/post/DX1A6LvEuhz": ("口誤", "職場口誤"),
    "https://www.threads.com/@saki44189/post/DX0ipUFibuQ": ("叫錯", None),
    "https://www.threads.com/@hhj_meow/post/DX1kw9bj6DL": ("走錯空間", None),
    "https://www.threads.com/@menshangsds10/post/DX4otZgGIfh": ("口誤", "職場口誤"),
    "https://www.threads.com/@doby_john/post/DX1McZTkWcY": ("被工作/兵役制約", None),
    "https://www.threads.com/@annanatw/post/DX2PFx9D5nP": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@_eli_taiwan/post/DX19nrGk9aL": ("當眾出糗", None),
    "https://www.threads.com/@wen_shin0305/post/DX12uGiiWhz": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@dancecloud824/post/DX1wRJ6mlAq": ("口誤", "職場口誤"),
    "https://www.threads.com/@changdori/post/DX05chTlDzC": ("口誤", "職場口誤"),
    "https://www.threads.com/@changdori/post/DX073O1lLdS": ("回覆原 PO", None),
    "https://www.threads.com/@ck1110_0/post/DX1LE49k9tF": ("回覆原 PO", None),

    # ── Batch 2 ──────────────────────────────────────────────────────────────
    "https://www.threads.com/@xu.a.n/post/DX1aCfzkeVz": ("回覆原 PO", None),
    "https://www.threads.com/@ivu_rubio/post/DX5VF1UkqgY": ("口誤", "腦袋當機"),
    "https://www.threads.com/@zizian940616/post/DX0uJo8juQe": ("口誤", "職場口誤"),
    "https://www.threads.com/@jamiesip_/post/DX0-KyEkaT_": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@ashlynfashlyn/post/DX0qJY-kXNR": ("口誤", "腦袋當機"),
    "https://www.threads.com/@viviancccjoe/post/DX1EpYlDzga": ("回覆原 PO", None),
    "https://www.threads.com/@viviancccjoe/post/DX1FDvYD1RX": ("回覆原 PO", None),
    "https://www.threads.com/@_.yuw039/post/DX2w_hqE7kV": ("被工作/兵役制約", None),
    "https://www.threads.com/@kumi03123/post/DX0LL3hkkgp": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@sugarhue.tw/post/DX1r4OBFE1C": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@phinas_ann/post/DX1JEjbE8BK": ("口誤", "職場口誤"),
    "https://www.threads.com/@mikosmart/post/DX2OJy6gUxt": ("其他", None),
    "https://www.threads.com/@abc7911162000/post/DX2BkcBE6_h": ("其他", None),
    "https://www.threads.com/@edward_liou8818/post/DX0uUXmGSuJ": ("其他", None),
    "https://www.threads.com/@edward_liou8818/post/DX4yIKlElKa": ("回覆原 PO", None),
    "https://www.threads.com/@lllyi_30/post/DX0UtqhAUtU": ("走錯空間", None),
    "https://www.threads.com/@lolala_0921/post/DX3QxGoE0XM": ("當眾出糗", None),
    "https://www.threads.com/@sappho.eureka/post/DX1TKLBkdvE": ("叫錯", None),
    "https://www.threads.com/@yyi_.0313/post/DX2asYQEyDu": ("當眾出糗", None),
    "https://www.threads.com/@hchengchih/post/DX1BYutCbDp": ("以為沒人亂講話", None),
    "https://www.threads.com/@ccasper_chouu/post/DX1FRR0kQnA": ("口誤", "職場口誤"),
    "https://www.threads.com/@lordnoodle_ty/post/DX16Yb7k04Z": ("當眾出糗", None),
    "https://www.threads.com/@lordnoodle_ty/post/DX17In3k8rz": ("回覆原 PO", None),
    "https://www.threads.com/@aa99770/post/DX2sM_Uk3VT": ("以為沒人亂講話", None),
    "https://www.threads.com/@claire.huang.359/post/DX12t4Vk0Rv": ("其他", None),
    "https://www.threads.com/@ting_ruu/post/DX3jHcJlCiA": ("回覆原 PO", None),
    "https://www.threads.com/@claire.huang.359/post/DX3jQOxk319": ("口誤", "點餐/購物"),
    "https://www.threads.com/@o33o_520/post/DX1tYVMDws5": ("口誤", "乳頭/奶頭"),
    "https://www.threads.com/@tiger_city_333/post/DX139yviVek": ("當眾出糗", None),
    "https://www.threads.com/@nikitanet/post/DX3JzrTER00": ("其他", None),
    "https://www.threads.com/@pear_6060/post/DX41b2wk-ix": ("口誤", "語言混亂"),
    "https://www.threads.com/@yuki6042002/post/DX3D155kft4": ("其他", None),
    "https://www.threads.com/@ms.mama3.0/post/DX36q3nDfCI": ("其他", None),
    "https://www.threads.com/@c.moon_99/post/DX0va9yAVak": ("回覆原 PO", None),
    "https://www.threads.com/@chichi.wu1007/post/DX1-r2tlLwU": ("以為在跟自己說話", None),
    "https://www.threads.com/@jialing_0509/post/DX4PiGkEQLu": ("口誤", "職場口誤"),
    "https://www.threads.com/@y._c_.h/post/DX4ToLCCazN": ("其他", None),
    "https://www.threads.com/@ora0717/post/DX0UBr_EiRx": ("當眾出糗", None),
    "https://www.threads.com/@johnwangcy/post/DX0QKT8Dzk1": ("口誤", "職場口誤"),
    "https://www.threads.com/@hagar520/post/DX3LoO2lGV-": ("當眾出糗", None),
    "https://www.threads.com/@lenaleom_/post/DX1I57Fkhgw": ("叫錯", None),
    "https://www.threads.com/@sammi19553/post/DX1DcnyEoV9": ("其他", None),
    "https://www.threads.com/@gino.bloodshield/post/DX1EASrCaiQ": ("口誤", "職場口誤"),
    "https://www.threads.com/@higginswale123/post/DX1xSVCAU6T": ("當眾出糗", "童言無忌"),
    "https://www.threads.com/@basara2023/post/DX0_Oi7EW46": ("被工作/兵役制約", "當完兵喊「有！」"),
    "https://www.threads.com/@girlvivilin2022/post/DX08Up9D_ef": ("當眾出糗", None),
    "https://www.threads.com/@girlvivilin2022/post/DX09qk1j9RR": ("回覆原 PO", None),
    "https://www.threads.com/@h625242/post/DX1sSNQmBqv": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@jjyiting/post/DX0WBy_ElIx": ("當眾出糗", None),
    "https://www.threads.com/@fr35680/post/DX0xd2lmE-1": ("回覆原 PO", None),
    "https://www.threads.com/@cheahnanyi/post/DX3neWBkgkN": ("以為在跟自己說話", None),
    "https://www.threads.com/@shanfon.hsu/post/DX2GMVnGa7f": ("當眾出糗", None),
    "https://www.threads.com/@kaya_0418_/post/DX0stPEErBT": ("當眾出糗", None),
    "https://www.threads.com/@a520lucky/post/DX0VUzVk96-": ("回覆原 PO", None),
    "https://www.threads.com/@bearaholics/post/DX0sln5GkBi": ("其他", None),
    "https://www.threads.com/@winshian/post/DX1pNA3kUVT": ("其他", None),
    "https://www.threads.com/@thewei_4111/post/DX1gLfMDyRS": ("當眾出糗", None),
    "https://www.threads.com/@thewei_4111/post/DX1gjkJjy0H": ("回覆原 PO", None),
    "https://www.threads.com/@o3ossn/post/DX0ukVgD7YE": ("其他", None),
    "https://www.threads.com/@o3ossn/post/DX0z_5wj5tG": ("回覆原 PO", None),
    "https://www.threads.com/@shen_1221/post/DX1LELSkTDP": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@se7en_730/post/DX3Aw41kSPh": ("回覆原 PO", None),
    "https://www.threads.com/@seven7.zou/post/DX16DgdD19p": ("其他", None),
    "https://www.threads.com/@zhangmeimeila/post/DX0rv7Ak7fs": ("口誤", "職場口誤"),
    "https://www.threads.com/@an595587/post/DX1HDrJgchb": ("回覆原 PO", None),
    "https://www.threads.com/@vivianlo5836/post/DX1Ju5OkwGR": ("當眾出糗", None),
    "https://www.threads.com/@eastgonechiang/post/DX3HY9OGI4A": ("以為沒人亂講話", None),
    "https://www.threads.com/@pun_/post/DX3JwLSCWaJ": ("口誤", "職場口誤"),
    "https://www.threads.com/@ratatoskleon/post/DX0nJ__k2ri": ("其他", None),
    "https://www.threads.com/@comedinebento/post/DX3la0hGOU9": ("口誤", "腦袋當機"),
    "https://www.threads.com/@gtoclark1124/post/DX0moSCk92u": ("當眾出糗", None),
    "https://www.threads.com/@fatcutedog0305/post/DX0DyWcATi9": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@tsaikuan/post/DX136WeExTK": ("口誤", "職場口誤"),
    "https://www.threads.com/@linwei0508/post/DX0_01DFBdD": ("以為沒人亂講話", None),
    "https://www.threads.com/@yoyoxai/post/DX2z7xmEz_O": ("當眾出糗", None),
    "https://www.threads.com/@yuni_skin_care/post/DX0c6pdEz4b": ("口誤", "腦袋當機"),
    "https://www.threads.com/@lucifer11_9/post/DX0Uk-lCQPj": ("走錯空間", None),
    "https://www.threads.com/@chia_yu/post/DX1LH3KEdYn": ("口誤", "點餐/購物"),
    "https://www.threads.com/@chia_yu/post/DX1Pr3mkW7M": ("回覆原 PO", None),
    "https://www.threads.com/@_1xy.z_/post/DX0aXgDmNmz": ("當眾出糗", None),

    # ── Batch 3 ──────────────────────────────────────────────────────────────
    "https://www.threads.com/@yancha0413/post/DX1dl9xAdci": ("口誤", "職場口誤"),
    "https://www.threads.com/@xiiian_foodie/post/DX1JScBEWiR": ("回覆原 PO", None),
    "https://www.threads.com/@wu_shawn_wu/post/DX1YvEbDxXN": ("其他", None),
    "https://www.threads.com/@loverbrain1020/post/DX0YZ3xkpzx": ("當眾出糗", None),
    "https://www.threads.com/@echin926/post/DX3SGVDExjf": ("其他", None),
    "https://www.threads.com/@zzztrhlzzz/post/DX016VUFMc9": ("回覆原 PO", None),
    "https://www.threads.com/@tian._.chi/post/DX1ERR3kYr9": ("當眾出糗", None),
    "https://www.threads.com/@1996.ct.28/post/DX1Kf_sE3M2": ("回覆原 PO", None),
    "https://www.threads.com/@notesfrommiss.t/post/DX1sy9mlLL5": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@guo_gu_/post/DX1AOOQkoRL": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@guo_gu_/post/DX1B8MhkkhB": ("回覆原 PO", None),
    "https://www.threads.com/@catbutler.tw/post/DX1uzStEQVD": ("口誤", "職場口誤"),
    "https://www.threads.com/@_7_______9_/post/DX3eAV6ESsv": ("走錯空間", None),
    "https://www.threads.com/@asiya_taiwan/post/DX1wONKCfRR": ("當眾出糗", None),
    "https://www.threads.com/@yu.omo0921/post/DX4SQMLjyT7": ("以為在跟自己說話", None),
    "https://www.threads.com/@sizune__sama/post/DX3Kg0dD8RL": ("以為沒人亂講話", None),
    "https://www.threads.com/@pink_chengvk/post/DX1v3vRGDS7": ("當眾出糗", None),
    "https://www.threads.com/@72040a/post/DX3RKwoERuD": ("被工作/兵役制約", None),
    "https://www.threads.com/@smhm_._hy/post/DX10eFNj-01": ("當眾出糗", None),
    "https://www.threads.com/@weiiiiii._.16/post/DX34-kxkdyG": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@wang_zu_xian/post/DX1gx3Ek6_m": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@ueose_807/post/DX1n8FrEbbd": ("以為沒人亂講話", None),
    "https://www.threads.com/@lisa.tsai.399/post/DX29JhSAa5L": ("以為沒人亂講話", None),
    "https://www.threads.com/@r.daenol/post/DX1hkNoD5wz": ("當眾出糗", "工作中"),
    "https://www.threads.com/@arieongo/post/DX0a5BTAYry": ("回覆原 PO", None),
    "https://www.threads.com/@grace5231/post/DX1Lm8vj28E": ("回覆原 PO", None),
    "https://www.threads.com/@yd_sam1006/post/DX1AB6lGbO6": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@ianciasmoo/post/DX4F_8iGGqK": ("以為沒人亂講話", None),
    "https://www.threads.com/@insomnia.xuan/post/DX4Xg5_gcoT": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@hitorimoyu2.0/post/DX3B248EtiT": ("當眾出糗", None),
    "https://www.threads.com/@hitorimoyu2.0/post/DX3LFDCErG3": ("回覆原 PO", None),
    "https://www.threads.com/@jack9455024/post/DX1jbijAYqV": ("口誤", "點餐/購物"),
    "https://www.threads.com/@summer.sammi/post/DX0zLpCkUDn": ("回覆原 PO", None),
    "https://www.threads.com/@avanlin/post/DX0fPoyD2dg": ("回覆原 PO", None),
    "https://www.threads.com/@mayday19990729/post/DX3LLehGzw-": ("回覆原 PO", None),
    "https://www.threads.com/@jislove0011/post/DX1D03Kk4Th": ("口誤", "腦袋當機"),
    "https://www.threads.com/@lovejclike/post/DX4T3bZlMo2": ("口誤", "職場口誤"),
    "https://www.threads.com/@iam_7_7/post/DX1Lennkiun": ("回覆原 PO", None),
    "https://www.threads.com/@venusk13724/post/DX1-ofZkxo6": ("其他", None),
    "https://www.threads.com/@yan_ears/post/DX3c85LDrni": ("回覆原 PO", None),
    "https://www.threads.com/@kido1935/post/DX2OW_rkuqn": ("走錯空間", None),
    "https://www.threads.com/@jaonrurisss/post/DX251AQmCrg": ("其他", None),
    "https://www.threads.com/@kai.12.18/post/DX1JddVk1EA": ("回覆原 PO", None),
    "https://www.threads.com/@sewingchoi.uk/post/DX2gun1ivZe": ("其他", None),
    "https://www.threads.com/@fridaiofficial/post/DX0v1v6mD3f": ("回覆原 PO", None),
    "https://www.threads.com/@mia_alan_naya/post/DX3dSnkjwCh": ("回覆原 PO", None),
    "https://www.threads.com/@wepbowepboinfinite/post/DX0U9AZkwFP": ("回覆原 PO", None),
    "https://www.threads.com/@reneenee_00_reneenee/post/DX0tObLE3w7": ("回覆原 PO", None),
    "https://www.threads.com/@kashasummerfin/post/DX0vSAelOPV": ("回覆原 PO", None),
    "https://www.threads.com/@tsuna0705._.sota0818/post/DX0xgEIiSa2": ("回覆原 PO", None),
    "https://www.threads.com/@vito19840327/post/DX1DsI6Gd7r": ("被工作/兵役制約", None),
    "https://www.threads.com/@yam830302/post/DX1tlq9E3WA": ("回覆原 PO", None),
    "https://www.threads.com/@suie125/post/DX1t_EQj3O5": ("回覆原 PO", None),
    "https://www.threads.com/@yan___8110/post/DX1FtfqAd4N": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@ericomando/post/DX2haYDE2BE": ("以為沒人亂講話", None),
    "https://www.threads.com/@xu__bin__666/post/DX0kdR7k-Hn": ("其他", None),
    "https://www.threads.com/@therock186/post/DX3Ox2DD0b1": ("回覆原 PO", None),
    "https://www.threads.com/@therock186/post/DX3QyMOjzG6": ("回覆原 PO", None),
    "https://www.threads.com/@make.in.uk/post/DX2YztxDUAw": ("其他", None),
    "https://www.threads.com/@rainstar1199/post/DX1pXnKCX0j": ("回覆原 PO", None),
    "https://www.threads.com/@yuan_yuan_2001/post/DX3GVE0mFgE": ("口誤", "語言混亂"),
    "https://www.threads.com/@yuan_yuan_2001/post/DX3Ln_xGDdu": ("回覆原 PO", None),
    "https://www.threads.com/@fatcutedog0305/post/DX0FEfNAfZ2": ("當眾出糗", None),
    "https://www.threads.com/@lph._0807/post/DX0wRXwFGAO": ("回覆原 PO", None),
    "https://www.threads.com/@leon0421/post/DXz6oaWE7Gj": ("回覆原 PO", None),
    "https://www.threads.com/@abukuan5566/post/DX0P9l4k8KP": ("其他", None),
    "https://www.threads.com/@s8vu0f8cjfc0/post/DXzzb44k0VR": ("當眾出糗", None),
    "https://www.threads.com/@zhang.jia.jun/post/DX1YhUtj6e3": ("當眾出糗", None),
    "https://www.threads.com/@wwweize/post/DX3Sv1YkmSP": ("當眾出糗", "工作中"),
    "https://www.threads.com/@wwweize/post/DX35RHMkowi": ("回覆原 PO", None),
    "https://www.threads.com/@masakisung/post/DX07TdAiW8I": ("以為沒人亂講話", None),
    "https://www.threads.com/@72040a/post/DX3QiLBEfm3": ("回覆原 PO", None),
    "https://www.threads.com/@owling0717/post/DX0qrheEX56": ("當眾出糗", None),
    "https://www.threads.com/@lulu_gu221/post/DX2BWi2GfmD": ("當眾出糗", None),
    "https://www.threads.com/@mickfu0819/post/DX2DWwiCUHu": ("口誤", "點餐/購物"),
    "https://www.threads.com/@abc3504421/post/DX0_iARGD0k": ("回覆原 PO", None),
    "https://www.threads.com/@secret0513/post/DX0W5RtiQo3": ("口誤", "職場口誤"),
    "https://www.threads.com/@dolce_gti0318/post/DX01q3FANrT": ("其他", None),
    "https://www.threads.com/@fang_0117/post/DX0sCszCVRJ": ("其他", None),
    "https://www.threads.com/@35.film.35/post/DX0hTUxmP93": ("叫錯", "叫老師媽媽"),

    # ── Batch 4 ──────────────────────────────────────────────────────────────
    "https://www.threads.com/@chuchuchen1001/post/DX0K2xRkkq0": ("回覆原 PO", None),
    "https://www.threads.com/@oreooreo_o/post/DX0KYlFGC2Z": ("當眾出糗", None),
    "https://www.threads.com/@kellytsai5609/post/DX4D1sPEwDG": ("當眾出糗", "童言無忌"),
    "https://www.threads.com/@hmg_kh_tw/post/DX0YS5dn4-f": ("被工作/兵役制約", None),
    "https://www.threads.com/@katie20700/post/DX0M0_0Ejzc": ("回覆原 PO", None),
    "https://www.threads.com/@ll_rn.26/post/DX2YjvBk1Sj": ("當眾出糗", None),
    "https://www.threads.com/@jayjay_tucker/post/DX3LE9JE2Mm": ("回覆原 PO", None),
    "https://www.threads.com/@arieongo/post/DX0ppCKAaVH": ("其他", None),
    "https://www.threads.com/@chloe_huangck/post/DX08AeqAaPv": ("回覆原 PO", None),
    "https://www.threads.com/@singlexhugxl/post/DX00adxEu5N": ("回覆原 PO", None),
    "https://www.threads.com/@lescherry710815/post/DX0-66-ERfZ": ("口誤", "腦袋當機"),
    "https://www.threads.com/@jipmeme/post/DX1IFCEmZtO": ("當眾出糗", None),
    "https://www.threads.com/@poop_shuo/post/DX4P967EdBI": ("以為沒人亂講話", None),
    "https://www.threads.com/@someone_finding_you/post/DX0Q3GLk6hO": ("其他", None),
    "https://www.threads.com/@shark._.cat.168/post/DX3AJTUGMBH": ("當眾出糗", None),
    "https://www.threads.com/@weichen_0104/post/DX2EeuxEhG6": ("其他", None),
    "https://www.threads.com/@unilions6566/post/DX0657lD86p": ("當眾出糗", None),
    "https://www.threads.com/@mugen.isfjsuspended/post/DX10kJ3kvrB": ("當眾出糗", None),
    "https://www.threads.com/@continuegamingbar/post/DX12frmkr-Z": ("當眾出糗", None),
    "https://www.threads.com/@_157_xuan/post/DXz3de1kzlr": ("回覆原 PO", None),
    "https://www.threads.com/@wu_shawn_wu/post/DX1ZuwtDxQS": ("其他", None),
    "https://www.threads.com/@jody0129chen/post/DX1qppAATOn": ("回覆原 PO", None),
    "https://www.threads.com/@zachary_tuuu/post/DX0Z0gHEvxq": ("回覆原 PO", None),
    "https://www.threads.com/@nini914/post/DX19gWHiRHe": ("口誤", "點餐/購物"),
    "https://www.threads.com/@ee_0816/post/DX2A0zXAZbz": ("口誤", "點餐/購物"),
    "https://www.threads.com/@hurricane_116/post/DX1hYM3kcyu": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@yoyo_1215106/post/DX1qaDcgfGr": ("當眾出糗", "童言無忌"),
    "https://www.threads.com/@e9264042/post/DX0PPJPk8y0": ("當眾出糗", None),
    "https://www.threads.com/@asummer612/post/DX1FRD6kdpE": ("當眾出糗", None),
    "https://www.threads.com/@countingstars888/post/DX0V6xck_WR": ("口誤", "職場口誤"),
    "https://www.threads.com/@cyy19920102/post/DX1woD7E4Q6": ("其他", None),
    "https://www.threads.com/@squall075/post/DX0WAg0AWya": ("當眾出糗", None),
    "https://www.threads.com/@lu_alumi/post/DX29eH9jU7G": ("口誤", "點餐/購物"),
    "https://www.threads.com/@ritsuko_hsu/post/DX1uyqwkdef": ("回覆原 PO", None),
    "https://www.threads.com/@elacheln/post/DX0KtZck2uD": ("回覆原 PO", None),
    "https://www.threads.com/@northlightdaniel/post/DXz_bu4kzb_": ("當眾出糗", None),
    "https://www.threads.com/@mothra_1961/post/DX0rD-MGVnI": ("口誤", "職場口誤"),
    "https://www.threads.com/@speed19881211/post/DX0sRRnktDd": ("回覆原 PO", None),
    "https://www.threads.com/@gracia__0205/post/DX1wZHPigjp": ("被工作/兵役制約", None),
    "https://www.threads.com/@siyu3876/post/DXzovnWk9P9": ("以為沒人亂講話", None),
    "https://www.threads.com/@clliud/post/DX2eZ9ekqmn": ("當眾出糗", None),
    "https://www.threads.com/@aurora_luna_sisters/post/DX3QUHakX0R": ("其他", None),
    "https://www.threads.com/@qqqqqq_0828/post/DX1n8hkmJEi": ("其他", None),
    "https://www.threads.com/@mushgoodlife/post/DX0OWxEE1o-": ("回覆原 PO", None),
    "https://www.threads.com/@nickryu_11/post/DX1yBO9E175": ("當眾出糗", None),
    "https://www.threads.com/@d212104/post/DX0H_XXgeQG": ("回覆原 PO", None),
    "https://www.threads.com/@evan_fanfan0.0/post/DX1pPRHETw0": ("當眾出糗", None),
    "https://www.threads.com/@ty3304588/post/DX0SVqRkiEq": ("口誤", "腦袋當機"),
    "https://www.threads.com/@1102_wen/post/DX0ZJBiEpFj": ("當眾出糗", None),
    "https://www.threads.com/@nuomeicai/post/DX2qleKklTd": ("口誤", "點餐/購物"),
    "https://www.threads.com/@wu_small_chi/post/DX00LfLj6_W": ("走錯空間", None),
    "https://www.threads.com/@soul_alchemy_sanctuary/post/DX0d0m3mecE": ("回覆原 PO", None),
    "https://www.threads.com/@kk_h_s_u/post/DX0FOz_E3LD": ("回覆原 PO", None),
    "https://www.threads.com/@heloise0301/post/DX0mJPDkTgm": ("口誤", "腦袋當機"),
    "https://www.threads.com/@bbddy._.04/post/DX4rIF2k86X": ("當眾出糗", None),
    "https://www.threads.com/@autumn_narwhal1019/post/DX0bxYQE8nt": ("回覆原 PO", None),
    "https://www.threads.com/@the.bryan989/post/DX0JT_uk7vQ": ("回覆原 PO", None),
    "https://www.threads.com/@sonicrockkimo/post/DX0aNawkzt5": ("當眾出糗", None),
    "https://www.threads.com/@e.sther_f/post/DX09hufD_CF": ("走錯空間", None),
    "https://www.threads.com/@mia_0819_99/post/DX0ZVVEE1EQ": ("當眾出糗", None),
    "https://www.threads.com/@parenting.connecting/post/DXzpxdOkxWD": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@a_ticking_time_bomb/post/DX0HwD1E7tW": ("回覆原 PO", None),
    "https://www.threads.com/@a_ticking_time_bomb/post/DX0Hcy-k3TN": ("回覆原 PO", None),
    "https://www.threads.com/@swia.mu/post/DX1ma2HCTCE": ("回覆原 PO", None),
    "https://www.threads.com/@evan_jhao/post/DX1mHqtE0sU": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@111111xuan/post/DX0mAyMiTYb": ("回覆原 PO", None),
    "https://www.threads.com/@zhuoyeshizhi/post/DX1oP5tGVAd": ("回覆原 PO", None),
    "https://www.threads.com/@7pao.tainan/post/DXzsF_nEulr": ("回覆原 PO", None),
    "https://www.threads.com/@hammer__lee/post/DX0YmnOE2g2": ("其他", None),
    "https://www.threads.com/@youzheng_ze0916/post/DX5lUeikat3": ("回覆原 PO", None),
    "https://www.threads.com/@t2ex0psmjx/post/DX1C1sfH1oH": ("被工作/兵役制約", None),
    "https://www.threads.com/@pppabo_0302/post/DX1wiAJGE_B": ("當眾出糗", "工作中"),
    "https://www.threads.com/@li_52_75/post/DX0TdXXE9nW": ("口誤", "腦袋當機"),
    "https://www.threads.com/@the_fungo/post/DX0urSgiRq8": ("口誤", "腦袋當機"),
    "https://www.threads.com/@millymaruko/post/DX4eB9BES8K": ("以為沒人亂講話", None),
    "https://www.threads.com/@cracraru0.0/post/DXzr5v4k-MQ": ("回覆原 PO", None),
    "https://www.threads.com/@jiangmarka/post/DX3K7lbk_q-": ("回覆原 PO", None),
    "https://www.threads.com/@yhwvivian/post/DX3h6vClOLj": ("口誤", "點餐/購物"),
    "https://www.threads.com/@yhwvivian/post/DX3l2IRlKKd": ("回覆原 PO", None),
    "https://www.threads.com/@17.16/post/DXzusgpEve0": ("當眾出糗", None),

    # ── Batch 5 ──────────────────────────────────────────────────────────────
    "https://www.threads.com/@wx_.knvn/post/DX0e4nOicsF": ("口誤", "語言混亂"),
    "https://www.threads.com/@_lorene27/post/DX0OZ6EEjcZ": ("其他", None),
    "https://www.threads.com/@catnine_728/post/DX1x98uCZnb": ("被工作/兵役制約", None),
    "https://www.threads.com/@furu_cafe_yoruni/post/DXz4NbYEz8h": ("回覆原 PO", None),
    "https://www.threads.com/@yifants/post/DX1nz8xjzHd": ("當眾出糗", None),
    "https://www.threads.com/@anna870719/post/DX1wY3xE67e": ("當眾出糗", None),
    "https://www.threads.com/@japanpatrolcar/post/DXzrgWzEw_Q": ("其他", None),
    "https://www.threads.com/@offteatiger/post/DX18ZZED6_L": ("回覆原 PO", None),
    "https://www.threads.com/@mintsy____/post/DX0MDyhk9BF": ("回覆原 PO", None),
    "https://www.threads.com/@enjoy__waves/post/DX0NrvbjxuS": ("回覆原 PO", None),
    "https://www.threads.com/@imdanatsai/post/DX0nEvLEpbW": ("回覆原 PO", None),
    "https://www.threads.com/@yuukiopp_67/post/DXzvWFqk6T7": ("當眾出糗", None),
    "https://www.threads.com/@tamama9487/post/DX0-5h9gVbA": ("回覆原 PO", None),
    "https://www.threads.com/@iaba661114/post/DX0LQUgkzm-": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@hankw_uu/post/DX0PZAxD979": ("口誤", "職場口誤"),
    "https://www.threads.com/@xyzec.tol9/post/DX4FKWICS5V": ("口誤", "腦袋當機"),
    "https://www.threads.com/@itsme_yuan0318/post/DX277aMmhC-": ("回覆原 PO", None),
    "https://www.threads.com/@ai__o9e5/post/DX1QJ9dj9Qg": ("認錯人", "沒有肢體接觸"),
    "https://www.threads.com/@hi_____eeeee/post/DXzsJ-igU_q": ("口誤", "腦袋當機"),
    "https://www.threads.com/@wu_shawn_wu/post/DX3eShMAIT9": ("回覆原 PO", None),
    "https://www.threads.com/@linsamsam1128/post/DX285FMkw6t": ("口誤", "職場口誤"),
    "https://www.threads.com/@popoqer123/post/DX2XsbXkk41": ("回覆原 PO", None),
    "https://www.threads.com/@claire.huang.359/post/DX0Mep2E2Ai": ("以為沒人亂講話", None),
    "https://www.threads.com/@claire.huang.359/post/DX0YE_Tk9dH": ("回覆原 PO", None),
    "https://www.threads.com/@hsp19820531/post/DX0mtJjkprh": ("回覆原 PO", None),
    "https://www.threads.com/@claire.huang.359/post/DX0m_LzEwd-": ("回覆原 PO", None),
    "https://www.threads.com/@insomi.cat/post/DXznIyyE_cc": ("當眾出糗", None),
    "https://www.threads.com/@leo91417/post/DXz3v2KEvjx": ("回覆原 PO", None),
    "https://www.threads.com/@cutieeeebae_/post/DXzlSjjnycE": ("回覆原 PO", None),
    "https://www.threads.com/@ziying212/post/DX0ZlCBk8-u": ("回覆原 PO", None),
    "https://www.threads.com/@olivia_112100/post/DX1IIt2CZFk": ("回覆原 PO", None),
    "https://www.threads.com/@oeddueyaqn/post/DX0P9QagZrM": ("回覆原 PO", None),
    "https://www.threads.com/@jiun1215_/post/DX0JzbYEgcw": ("回覆原 PO", None),
    "https://www.threads.com/@vivian_super.junior/post/DX3IS4sD5Ns": ("走錯空間", None),
    "https://www.threads.com/@ru_0109/post/DX0bYASEWdW": ("其他", None),
    "https://www.threads.com/@spectre1201/post/DX0o6gUHxyn": ("回覆原 PO", None),
    "https://www.threads.com/@jerrykuo1224/post/DX1iGWjE4b0": ("口誤", "腦袋當機"),
    "https://www.threads.com/@crazydiamond9786/post/DX2TEBAkkzV": ("回覆原 PO", None),
    "https://www.threads.com/@dohow37/post/DXzt-LikyTa": ("回覆原 PO", None),
    "https://www.threads.com/@jcc_tw/post/DX0GSpmE09G": ("走錯空間", None),
    "https://www.threads.com/@lovemon33/post/DX0bFpdkU8I": ("回覆原 PO", None),
    "https://www.threads.com/@fih_fish/post/DX1ZNoLGCZN": ("以為沒人亂講話", None),
    "https://www.threads.com/@pen9u1n25/post/DXz_qQAEwiW": ("其他", None),
    "https://www.threads.com/@paradox1025/post/DX0rXm2CUkH": ("回覆原 PO", None),
    "https://www.threads.com/@ray0720_0615/post/DX0_xkDkUUh": ("回覆原 PO", None),
    "https://www.threads.com/@chi_chi_06_02/post/DX1CKORGl35": ("回覆原 PO", None),
    "https://www.threads.com/@richchen518/post/DX0Nv6ek5mz": ("被工作/兵役制約", "一起說歡迎光臨"),
    "https://www.threads.com/@cheen_hwang/post/DX0ov8zESQn": ("回覆原 PO", None),
    "https://www.threads.com/@mr.pumpkin_0930/post/DXzr9_Skjdb": ("走錯空間", None),
    "https://www.threads.com/@roc_happy_john/post/DX0CojqErVy": ("回覆原 PO", None),
    "https://www.threads.com/@shc19960327/post/DX0KE4Lk_0V": ("回覆原 PO", None),
    "https://www.threads.com/@1130._.hh/post/DX3zcJxAfMM": ("回覆原 PO", None),
    "https://www.threads.com/@thee_bursst_gg/post/DX0WkG4E69Y": ("回覆原 PO", None),
    "https://www.threads.com/@coldmeteor.akan/post/DX1pDECEkPx": ("回覆原 PO", None),
    "https://www.threads.com/@always_lch11/post/DX2G1IBGSax": ("當眾出糗", None),
    "https://www.threads.com/@minicooper240/post/DXz7aAME799": ("回覆原 PO", None),
    "https://www.threads.com/@yaobao0314/post/DX1s2H3kkW1": ("當眾出糗", None),
    "https://www.threads.com/@ck_marvin/post/DX1PV3Ykz-Y": ("當眾出糗", None),
    "https://www.threads.com/@o1_ynnyi/post/DX3AyfnERbv": ("當眾出糗", None),
    "https://www.threads.com/@lucastsai950429/post/DX4GhFhlEQl": ("回覆原 PO", None),
    "https://www.threads.com/@anry_yeh/post/DX3f92Ekveg": ("認錯人", "有肢體接觸"),
    "https://www.threads.com/@vaneppxx/post/DX4jKEKjOo1": ("當眾出糗", None),
    "https://www.threads.com/@__ni_ni1111/post/DX1Sne5iTGC": ("回覆原 PO", None),
    "https://www.threads.com/@kianest/post/DX1cOhGExxV": ("以為沒人亂講話", None),
    "https://www.threads.com/@xinting_zhou/post/DX2l-9Uk_If": ("口誤", "點餐/購物"),
    "https://www.threads.com/@jiugen_/post/DX0AIZLk42G": ("以為在跟自己說話", None),
    "https://www.threads.com/@navigator_x/post/DX0NoXjEt-D": ("回覆原 PO", None),
    "https://www.threads.com/@vox120219/post/DX0QhvHErKo": ("回覆原 PO", None),
    "https://www.threads.com/@chiara._.0503/post/DX0RrRcE4Wr": ("回覆原 PO", None),
    "https://www.threads.com/@sakra0018/post/DX1mxwRgYac": ("當眾出糗", None),
    "https://www.threads.com/@lupin_0516/post/DX0bNvQiQSy": ("回覆原 PO", None),
    "https://www.threads.com/@mmt.tang/post/DXztgmPk3AQ": ("回覆原 PO", None),
    "https://www.threads.com/@27_lun/post/DX2s5-xEwkp": ("回覆原 PO", None),
    "https://www.threads.com/@rutin_ved/post/DX0Oq8Bk0Or": ("回覆原 PO", None),
    "https://www.threads.com/@_000000_12399/post/DX0a_fEk5JR": ("以為沒人亂講話", None),
    "https://www.threads.com/@born2shine_1128/post/DX0zdbcEnGg": ("當眾出糗", None),
    "https://www.threads.com/@idv_hc/post/DX1Oc6mEVQ6": ("以為沒人亂講話", None),
    "https://www.threads.com/@cat.hua.519/post/DX1Q9I2EWWw": ("當眾出糗", None),
    "https://www.threads.com/@unalin615/post/DX1RJMTGf3M": ("回覆原 PO", None),
    "https://www.threads.com/@cat.hua.519/post/DX1RQB0EbHp": ("回覆原 PO", None),
    "https://www.threads.com/@shiou0114/post/DX0Ow9TE7gU": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@jain_jain_no1/post/DX0Z6wcCcDW": ("回覆原 PO", None),
    "https://www.threads.com/@belindagotravel/post/DX0x_eEE69R": ("其他", None),
    "https://www.threads.com/@hc_toy_0101/post/DXzq3pxkwv-": ("回覆原 PO", None),
    "https://www.threads.com/@bluesman0923/post/DX0gzrtgdI2": ("回覆原 PO", None),
    "https://www.threads.com/@eddie0205/post/DXzu4CCE81B": ("以為在跟自己說話", "以為店員在跟自己說話"),
    "https://www.threads.com/@yeungtszyung/post/DX0QEaCgUm2": ("回覆原 PO", None),
    "https://www.threads.com/@ben.chasing.winds/post/DXzfEnRk9HT": ("回覆原 PO", None),
    "https://www.threads.com/@emc_txt_army0728/post/DX1aP_rj2Xh": ("當眾出糗", None),
    "https://www.threads.com/@woonnie0555/post/DX0T1jWk9nn": ("回覆原 PO", None),
    "https://www.threads.com/@litinalee/post/DX2E5AuiEbH": ("回覆原 PO", None),
    "https://www.threads.com/@zheng_tsai_/post/DX2NJsiASH9": ("回覆原 PO", "留 X 看"),
    "https://www.threads.com/@jinbing0320/post/DX0e5p4kznc": ("回覆原 PO", None),
    "https://www.threads.com/@kaia_zzzzz/post/DX24qp1j1Fq": ("回覆原 PO", None),
    "https://www.threads.com/@dingdong000/post/DX0fGrVk0PG": ("回覆原 PO", None),
    "https://www.threads.com/@peterdart_s/post/DX0TwFjj1PS": ("回覆原 PO", None),
    "https://www.threads.com/@asdf.0708/post/DX1zZQsHQ3s": ("口誤", "職場口誤"),
    "https://www.threads.com/@st90621/post/DX13zEuEypB": ("回覆原 PO", None),
    "https://www.threads.com/@chichiaiii/post/DX3ULTXEvuF": ("其他", None),
    "https://www.threads.com/@kaixin1388/post/DX1YReXkZ_O": ("回覆原 PO", None),
    "https://www.threads.com/@adosi_howtodo/post/DX0-Q3yj_Bl": ("口誤", "語言混亂"),
    "https://www.threads.com/@foolman8291/post/DX0RskAEwR2": ("以為沒人亂講話", None),
    "https://www.threads.com/@dddd12111219/post/DX17IWYk2Lj": ("當眾出糗", None),
    "https://www.threads.com/@melody10210118/post/DXzrxr2k9_m": ("被工作/兵役制約", "一起說歡迎光臨"),
    "https://www.threads.com/@neck0603/post/DX4DBQsknUG": ("走錯空間", None),
    "https://www.threads.com/@asiankilljoy_/post/DX0UXxBCSvh": ("回覆原 PO", "留 X 看"),
}


def main():
    out = {url: {"category": cat, "subcategory": sub}
           for url, (cat, sub) in OVERRIDES.items()}

    out_path = DATA / 'category-overrides.json'
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"Written {len(out)} overrides → {out_path}")

    from collections import Counter
    cats = Counter(v["category"] for v in out.values())
    print("\nBreakdown (all 426):")
    for cat, n in cats.most_common():
        print(f"  {n:4d}  {cat}")


if __name__ == "__main__":
    main()
